# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'



target 'ExternalPackages' do

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!

    pod 'Alamofire', '~> 1.2'
    
    pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git'

end

target 'ExternalPackagesTests' do

end

